version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest 
    container_name: uniservice_db
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Uniservicio58414555
    volumes:
      - sql_data:/var/opt/mssql
      # Mapea tus archivos .sql (01, 02, 03...)
      - ./database:/docker-entrypoint-initdb.d
      # Mapea el script .sh a la raíz para que el entrypoint lo encuentre
      - ./import-data.sh:/import-data.sh
    # Inicia SQL y el script de carga en paralelo
    entrypoint: /bin/bash -c "/import-data.sh & /opt/mssql/bin/sqlservr"
    
volumes:
  sql_data: